apiVersion: batch/v1
kind: Job
metadata:
  name: "docker-example"
  namespace: mlflow
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 6
  template:
    spec:
      containers:
        - name: "docker-example"
          image: "280883893231.dkr.ecr.ap-northeast-1.amazonaws.com/mlflow-kubernetes-example:latest"
          command: [""]
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
      restartPolicy: Never
